Feature/dso 847
ministryofjustice/digital-studio-infra pull request #462
Opened 2021-03-29 12:44 UTC by wullub

2021-04-09 16:26 UTC, ynyrllw requested changes
the GHA check doesn't work and when I do a local plan i get a similar error with duplicate variables.

2021-04-09 16:33 UTC, ynyrllw commented on shared/apps/iis.tf
> +
this shared directory is for sharing betweens different apps. This file would be more appropriate in the iis directory.

2021-04-09 16:38 UTC, ynyrllw commented on webops/dev/env.hcl
> +# Set common variables for the environment. This is automatically pulled in in the root terragrunt.hcl configuration to
not sure where this file is from - webops doesn't use terragrunt and I don't recognise a qa environment in it, + there is no other webops change here

2021-04-09 16:45 UTC, ynyrllw commented on shared/apps/iis.tf
> +resource "azurerm_dns_cname_record" "cname" {
this isn't right for iis stage. Plan should be showing this right?

for dev its https://hpa-stage.hmpps.dsd.io it doesn't have service + the rg name is prod

2021-04-09 16:50 UTC, ynyrllw commented on iis/prod/variables.tf
> +  github_deploy_branch = "deploy-to-${var.env}"
we should be able to get rid of this variable now as its not used, i think

2021-04-09 16:55 UTC, ynyrllw commented on iis/stage/variables.tf
> +  dns_name = "hpa-${var.env}"
don't think this is used

2021-04-09 17:14 UTC, ynyrllw commented
left some comments on the plan not working for IIS envs, haven't checked the others but once this is fixed i might check the rest.

good work on tidying/adding variables. There may be some variables which could be moved out and used by all the apps e.g. documents.

It would be good to provide some high level description in either the PR or commit messages on the change as I can't spot any and this is a big ish change so would expect even more description explaining.

When i refactored this recently I abstracted quite alot already to modularise all the apps as they're infrastrucutre is (somewhat) similar. There needs to be a balance to how far you abstract out vs simpilicity/understanding and IMO this adds a whole other layer of abstraction on top of something that's pretty complex already.

2021-04-12 10:03 UTC, ynyrllw commented on iis/preprod/sql-user-passwords.tf
> +# resource "random_id" "sql-users-passwords" {
what was wrong using this? it would reduce code duplication as now you have 4 resource blocks instead of just using a list of users.

2021-04-12 10:33 UTC, wullub commented on iis/preprod/sql-user-passwords.tf
> +# resource "random_id" "sql-users-passwords" {
having a list is a better idea It's what i wanted to implement. But because these resources have already been created individually not from a list, when having them generated from a list terraform recognises it as a different thing and would destroy and recreate. That's why i didn't implement generating them from a list and just left a comment to show how it could be done if recreating the passwords would be ok . I was thinking this would be good for a separate PR

2021-04-12 11:18 UTC, ynyrllw submitted a review, later dismissed

2021-04-12 13:16 UTC, reallydontask commented on iis/prod/terraform.tfvars
> +https_only  = false
shouldn't this be true?

it's a bit odd that preprod is https only but prod isn't?

2021-04-12 13:16 UTC, reallydontask commented on azure-prod.tf
>    default = "5b2509b1-64bd-4117-b839-9b0c2b02e02c"
A generic comment on this is that the symlink means that we have azure-prod inside preprod which is certainly confusing, whould suggest a rename

2021-04-12 13:16 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +        run: |
in dso-azure-infra-ad, you can select aazure_and_client_Secret and it will create two secrets

One as required by azure/login the other just the client secret itself.

That way you don't need to do this

2021-04-12 13:16 UTC, reallydontask requested changes

2021-04-12 13:16 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +          echo "ARM_CLIENT_ID=`echo ${{ secrets.DIGITAL_STUDIO_INFRA_PROD }} | sed 's/.*clientId:\([^ ]*\).*/\1/g'`" >> $GITHUB_ENV
in dso-azure-infra-ad, you can select aazure_and_client_Secret and it will create two secrets

One as required by azure/login the other just the client secret itself.

That way you don't need to do this

2021-04-12 14:31 UTC, wullub commented on azure-devtest.tf
> +variable "azure_git_repo_app_oid" {
yep, thing created by ds-infra-azure-ad, e.g. https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/b11478e9-3ca6-40b8-bbcd-9cb46c02957c/isMSAApp/

2021-04-12 14:31 UTC, wullub commented on azure-prod.tf
>    default = "5b2509b1-64bd-4117-b839-9b0c2b02e02c"
renaming could make it clearer, but that isn't something from this PR, and i'd like to not add anything new to this behemoth

2021-04-12 14:31 UTC, wullub commented on iis/iis.tf
> +    # DB_PASS        = random_id.sql-users-passwords["iisuser"].b64_url
it could be. I just want to change to the user passwords being generated from a list at a later date, not as separate resource blocks as it is now. But I'm trying to limit the scope of what this PR does

2021-04-12 14:31 UTC, wullub commented on iis/prod/terraform.tfvars
> +https_only  = false
i agree, but that's what the current state is and i don't want this PR to be making any changes to the infra. It's too big already

2021-04-12 14:31 UTC, wullub commented on iis/stage/variables.tf
> +  dns_name = "hpa-${var.env}"
it is in iis.tf

2021-04-12 14:31 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
> +          echo "ARM_CLIENT_ID=`echo ${{ secrets.DIGITAL_STUDIO_INFRA_PROD }} | sed 's/.*clientId:\([^ ]*\).*/\1/g'`" >> $GITHUB_ENV
added to https://github.com/ministryofjustice/dso-infra-azure-ad/pull/89

2021-04-12 14:31 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
> +          echo "ARM_CLIENT_ID=`echo ${{ secrets.DIGITAL_STUDIO_INFRA_PROD }} | sed 's/.*clientId:\([^ ]*\).*/\1/g'`" >> $GITHUB_ENV
i'll correct this when adding the ability for this GHA to deploy

2021-04-12 14:33 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
> +          echo "ARM_CLIENT_ID=`echo ${{ secrets.DIGITAL_STUDIO_INFRA_PROD }} | sed 's/.*clientId:\([^ ]*\).*/\1/g'`" >> $GITHUB_ENV
added to ministryofjustice/dso-infra-azure-ad#89
i'll correct this when giving the GHA the ability to deploy

2021-04-12 14:49 UTC, reallydontask commented on iis/prod/terraform.tfvars
> +https_only  = false
Fine, can you raise a jira to address this please?

2021-04-12 14:50 UTC, reallydontask commented on azure-prod.tf
>    default = "5b2509b1-64bd-4117-b839-9b0c2b02e02c"
I disagree, you are doing a refactor so this is the time to do it but it's up to you

2021-04-12 14:51 UTC, reallydontask commented on iis/iis.tf
> +    # DB_PASS        = random_id.sql-users-passwords["iisuser"].b64_url
> But I'm trying to limit the scope of what this PR does

I'm afraid that you've failed there 😉

2021-04-12 15:12 UTC, reallydontask approved these changes

2021-04-12 15:53 UTC, wullub commented on iis/prod/terraform.tfvars
> +https_only  = false
https://dsdmoj.atlassian.net/browse/DSO-881

2021-04-13 12:30 UTC, ynyrllw commented on iis/prod/terraform.tfvars
> +https_only  = false
wanted to mention for this I made some changes like these to the app services for dev/preprod on the project but have not been brave enough to do it to live as i didn't want to impact it. There are slight differences across all these projects that should be synced up at some point also if we are planning to make changes.

2021-04-13 12:31 UTC, ynyrllw commented on iis/prod/terraform.tfvars
> +https_only  = false
although there were some changes like this which didn't make sense that was already there

2021-04-13 12:31 UTC, ynyrllw approved these changes

2021-04-13 12:32 UTC, merged