test
ministryofjustice/digital-studio-infra pull request #476
Opened 2021-04-13 13:25 UTC by wullub

2021-04-14 09:58 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod environment: 
```
[command]/home/runner/work/_temp/d28d4630-1ecf-443d-aa49-9e684115ef97/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 09:59 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod environment: 
```
[command]/home/runner/work/_temp/e6c81b56-9f71-44ef-bb7b-1ad43328ed4c/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:07 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/63195496-e42b-4d9c-bc29-37fde697d482/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:43 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/f2ab0bf3-0793-42fe-b6c2-ef4fda0e15c4/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:50 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/24fce1f0-54f1-462d-a86a-1babb237d2d0/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:50 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/f182ee0e-cbdf-4bd1-ae43-30340a2c50cf/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:58 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/9991c251-4f7e-4299-b3e3-8c521ba110eb/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 11:58 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/576d18d7-7dfd-416e-9f15-751610a77ef0/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 12:04 UTC, hmpps-dso-automation commented
Terraform plan output in iis/prod: 
```
[command]/home/runner/work/_temp/582e16ac-25b3-41b4-b4af-78ec8201afbd/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 12:04 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/4759ba6d-8066-4d5e-8f5d-062ee794a3bc/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 12:04 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/c2e8ad8d-51de-4dc4-b0ba-d9b0713ea95f/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 14:37 UTC, reallydontask requested changes
Can you  tidy up the conditions as per comments please?

2021-04-14 14:37 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +        if: ${{ github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'schedule' }}
Guessing this is a copy and paste as there is no schedule defined, nor indeed any push

2021-04-14 14:37 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +        if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
there is no push on your triggers so this condition is odd.

I must confess that I'm not 100% whether **github.event.pull_request.merged** is enough

2021-04-14 14:37 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +      # - name: define arm vars
I would remove this step

2021-04-14 14:37 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
the environment is empty, what did you have in mind to add here?

2021-04-14 14:37 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
are you not able to have a variable here?

2021-04-14 14:48 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
> +        if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
I think the above will work

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

> If the action is closed and the merged key is false, the pull request was closed with unmerged commits. If the action is closed and the merged key is true, the pull request was merged.

2021-04-14 15:29 UTC, hmpps-dso-automation commented
Terraform plan output in iis/prod: 
```
[command]/home/runner/work/_temp/4286c997-6bae-41ce-93a4-89b6d0404b18/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 15:29 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/a8c0cfc8-3b98-48aa-b8df-198e0865ee11/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-14 15:30 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/0ef4effa-4946-4bf2-b958-4737722d5118/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-15 15:56 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
> +        if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
added push condition

2021-04-15 15:57 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
i like that the state of them show here https://github.com/ministryofjustice/digital-studio-infra so you can see if any of the builds are failing

2021-04-15 15:59 UTC, wullub commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
when I tried ${{ env.ENVIRONMENT }} it didn't work

2021-04-16 07:42 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
That's cool, I didn't know about that, learnt one thing today, can go home now 🤔

2021-04-16 07:42 UTC, reallydontask commented on .github/workflows/plan_iis_preprod.yml
>      environment: iis/preprod
fair enough

2021-04-16 07:52 UTC, reallydontask commented on azure-devtest.tf
> +variable "azure_repo_app_principle_oid" {
it's _principal_ rather than _principle_.

2021-04-16 07:53 UTC, reallydontask commented on shared/modules/azure-app-service/variables.tf
> +variable "azure_repo_app_principle_oid" {
This objectId is different to the other two, is this a personal SP you were using?

2021-04-16 07:56 UTC, reallydontask requested changes
please fix the typo

2021-04-16 08:30 UTC, hmpps-dso-automation commented
Terraform plan output in iis/prod: 
```
[command]/home/runner/work/_temp/4f99b668-6a14-4d5c-8fbb-b2cb486f502e/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 08:30 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/de3c0691-76de-4e8e-aabd-b34dac6ad9df/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 08:30 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/c3c277cd-c39e-46f8-8ce7-eec23dbd25f5/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 08:31 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/60655ab7-7597-4668-a5f2-8cff42456bb1/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 08:31 UTC, hmpps-dso-automation commented
Terraform plan output in iis/stage: 
```
[command]/home/runner/work/_temp/83cdf171-c311-4247-8b55-b19e70d4d0fc/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 08:31 UTC, hmpps-dso-automation commented
Terraform plan output in iis/prod: 
```
[command]/home/runner/work/_temp/7b91b216-56a8-4c97-88b4-9402c236bd25/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 09:17 UTC, hmpps-dso-automation commented
Terraform plan output in iis/preprod: 
```
[command]/home/runner/work/_temp/12c00908-6dd8-4b68-a187-02e9d5862747/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-16 09:20 UTC, reallydontask approved these changes

2021-04-16 09:39 UTC, dteelingmoj approved these changes
LGTM

2021-04-16 09:43 UTC, merged