add webops gha
ministryofjustice/digital-studio-infra pull request #480
Opened 2021-04-20 13:07 UTC by wullub

2021-04-21 15:37 UTC, hmpps-dso-automation commented
Terraform plan output in webops/dev: 
```
[command]/home/runner/work/_temp/88729440-b0e6-41d2-bf81-dd491dd0ce4d/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-22 09:11 UTC, hmpps-dso-automation commented
Terraform plan output in webops/prod: 
```
[command]/home/runner/work/_temp/996e7463-3094-49dd-8f01-1e0246a96458/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_key_vault.webops_jenkins will be updated in-place
  ~ resource "azurerm_key_vault" "webops_jenkins" {
      ~ access_policy                   = [
            # (3 unchanged elements hidden)
            {
                application_id          = ""
                certificate_permissions = []
                key_permissions         = []
                object_id               = "880790d6-77d8-4f9b-9df7-f60097801381"
                secret_permissions      = [
                    "Set",
                    "Get",
                ]
                storage_permissions     = []
                tenant_id               = "747381f4-e81f-4a43-bf68-ced6a1e14edf"
            },
          ~ {
              ~ object_id               = "a3415938-d0a1-4cfe-b312-edf87c251a69" -> "11efc5bf-0012-4a0f-ae6b-d21f1c43f251"
                # (6 unchanged elements hidden)
            },
          ~ {
              ~ object_id               = "4a65e4b7-189c-4d87-980a-050b9969009d" -> "c666e4d6-6452-42b9-ab84-0df839c4aa65"
                # (6 unchanged elements hidden)
            },
        ]
        id                              = "/subscriptions/a5ddf257-3b21-4ba9-a28c-ab30f751b383/resourceGroups/webops-prod/providers/Microsoft.KeyVault/vaults/webops-jenkins-prod"
        name                            = "webops-jenkins-prod"
        tags                            = {
            "application"      = "Management"
            "environment_name" = "prod"
            "service"          = "FixNGo"
        }
        # (12 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider



------------------------------------------------------------------------

This plan was saved to: tf.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "tf.plan"

::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0AAn execution plan has been generated and is shown below.%0AResource actions are indicated with the following symbols:%0A  ~ update in-place%0A%0ATerraform will perform the following actions:%0A%0A  # azurerm_key_vault.webops_jenkins will be updated in-place%0A  ~ resource "azurerm_key_vault" "webops_jenkins" {%0A      ~ access_policy                   = [%0A            # (3 unchanged elements hidden)%0A            {%0A                application_id          = ""%0A                certificate_permissions = []%0A                key_permissions         = []%0A                object_id               = "880790d6-77d8-4f9b-9df7-f60097801381"%0A                secret_permissions      = [%0A                    "Set",%0A                    "Get",%0A                ]%0A                storage_permissions     = []%0A                tenant_id               = "747381f4-e81f-4a43-bf68-ced6a1e14edf"%0A            },%0A          ~ {%0A              ~ object_id               = "a3415938-d0a1-4cfe-b312-edf87c251a69" -> "11efc5bf-0012-4a0f-ae6b-d21f1c43f251"%0A                # (6 unchanged elements hidden)%0A            },%0A          ~ {%0A              ~ object_id               = "4a65e4b7-189c-4d87-980a-050b9969009d" -> "c666e4d6-6452-42b9-ab84-0df839c4aa65"%0A                # (6 unchanged elements hidden)%0A            },%0A        ]%0A        id                              = "/subscriptions/a5ddf257-3b21-4ba9-a28c-ab30f751b383/resourceGroups/webops-prod/providers/Microsoft.KeyVault/vaults/webops-jenkins-prod"%0A        name                            = "webops-jenkins-prod"%0A        tags                            = {%0A            "application"      = "Management"%0A            "environment_name" = "prod"%0A            "service"          = "FixNGo"%0A        }%0A        # (12 unchanged attributes hidden)%0A%0A%0A        # (2 unchanged blocks hidden)%0A    }%0A%0APlan: 0 to add, 1 to change, 0 to destroy.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A%0A------------------------------------------------------------------------%0A%0AThis plan was saved to: tf.plan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tf.plan"%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0AAn execution plan has been generated and is shown below.%0AResource actions are indicated with the following symbols:%0A  ~ update in-place%0A%0ATerraform will perform the following actions:%0A%0A  # azurerm_key_vault.webops_jenkins will be updated in-place%0A  ~ resource "azurerm_key_vault" "webops_jenkins" {%0A      ~ access_policy                   = [%0A            # (3 unchanged elements hidden)%0A            {%0A                application_id          = ""%0A                certificate_permissions = []%0A                key_permissions         = []%0A                object_id               = "880790d6-77d8-4f9b-9df7-f60097801381"%0A                secret_permissions      = [%0A                    "Set",%0A                    "Get",%0A                ]%0A                storage_permissions     = []%0A                tenant_id               = "747381f4-e81f-4a43-bf68-ced6a1e14edf"%0A            },%0A          ~ {%0A              ~ object_id               = "a3415938-d0a1-4cfe-b312-edf87c251a69" -> "11efc5bf-0012-4a0f-ae6b-d21f1c43f251"%0A                # (6 unchanged elements hidden)%0A            },%0A          ~ {%0A              ~ object_id               = "4a65e4b7-189c-4d87-980a-050b9969009d" -> "c666e4d6-6452-42b9-ab84-0df839c4aa65"%0A                # (6 unchanged elements hidden)%0A            },%0A        ]%0A        id                              = "/subscriptions/a5ddf257-3b21-4ba9-a28c-ab30f751b383/resourceGroups/webops-prod/providers/Microsoft.KeyVault/vaults/webops-jenkins-prod"%0A        name                            = "webops-jenkins-prod"%0A        tags                            = {%0A            "application"      = "Management"%0A            "environment_name" = "prod"%0A            "service"          = "FixNGo"%0A        }%0A        # (12 unchanged attributes hidden)%0A%0A%0A        # (2 unchanged blocks hidden)%0A    }%0A%0APlan: 0 to add, 1 to change, 0 to destroy.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A%0A------------------------------------------------------------------------%0A%0AThis plan was saved to: tf.plan%0A%0ATo perform exactly these actions, run the following command to apply:%0A    terraform apply "tf.plan"%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-22 09:11 UTC, hmpps-dso-automation commented
Terraform plan output in webops/dev: 
```
[command]/home/runner/work/_temp/3dffca13-24e3-4b0b-a399-503fc2147258/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-22 09:29 UTC, dominicrobinson-moj submitted a review, later dismissed

2021-04-22 10:37 UTC, hmpps-dso-automation commented
Terraform plan output in webops/prod: 
```
[command]/home/runner/work/_temp/3366674c-2dad-44cc-85e8-8a26ca30d29c/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-22 10:37 UTC, hmpps-dso-automation commented
Terraform plan output in webops/dev: 
```
[command]/home/runner/work/_temp/7d77a2ac-7783-4547-8333-8b1da7f84f29/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-22 11:08 UTC, dominicrobinson-moj approved these changes

2021-04-22 16:11 UTC, bkennettmoj approved these changes
LGTM

2021-04-23 07:34 UTC, reallydontask requested changes
I checked the app and admin consent hadn't been granted.

Using the objectId is potentially problematic

2021-04-23 07:34 UTC, reallydontask commented on webops/prod/jenkins-keyvault.tf
>    access_policy {
I think this should be the way it was before

2021-04-23 08:23 UTC, wullub commented on webops/prod/jenkins-keyvault.tf
>    access_policy {
why? This needs less privileges and as far as i'm aware the object id isn't a security risk

2021-04-23 08:54 UTC, ynyrllw commented on webops/prod/jenkins-keyvault.tf
>    access_policy {
think i agree with Agoney of using the resource reference from data source instead of hardcoding. Unless there is issues using that.

2021-04-23 09:26 UTC, wullub commented on webops/prod/jenkins-keyvault.tf
>    access_policy {
yeah it needs service principal admin consent if we want to do a lookup. If we're going to give that we could put do lookups of all sp oids in the repo but unsure about granting that access

2021-04-23 09:28 UTC, merged

2021-04-23 09:30 UTC, hmpps-dso-automation reviewed
Terraform plan output in webops/dev: 
```
[command]/home/runner/work/_temp/328443db-2181-42a9-a79a-148918dbd3d4/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-23 09:30 UTC, hmpps-dso-automation reviewed
Terraform plan output in webops/prod: 
```
[command]/home/runner/work/_temp/387919de-b3ad-41c4-8206-7656f3fbe2eb/terraform-bin plan -out=tf.plan -refresh=false -no-color
Acquiring state lock. This may take a few moments...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider


Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0ANo changes. Infrastructure is up-to-date.%0A%0AThis means that Terraform did not detect any differences between your%0Aconfiguration and real physical resources that exist. As a result, no%0Aactions need to be performed.%0A%0AWarning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider%0A%0A%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-23 09:30 UTC, hmpps-dso-automation reviewed
Terraform apply output in webops/dev: 
```
[command]/home/runner/work/_temp/328443db-2181-42a9-a79a-148918dbd3d4/terraform-bin apply -auto-approve -no-color tf.plan
Acquiring state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0AApply complete! Resources: 0 added, 0 changed, 0 destroyed.%0AReleasing state lock. This may take a few moments...%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0AApply complete! Resources: 0 added, 0 changed, 0 destroyed.%0AReleasing state lock. This may take a few moments...%0A
::set-output name=stderr::
::set-output name=exitcode::0
```

2021-04-23 09:30 UTC, hmpps-dso-automation reviewed
Terraform apply output in webops/prod: 
```
[command]/home/runner/work/_temp/387919de-b3ad-41c4-8206-7656f3fbe2eb/terraform-bin apply -auto-approve -no-color tf.plan
Acquiring state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...

Outputs:

service_hmpps_dsd_io_namesevers = [
  toset([
    "ns1-06.azure-dns.com.",
    "ns2-06.azure-dns.net.",
    "ns3-06.azure-dns.org.",
    "ns4-06.azure-dns.info.",
  ]),
]
::debug::Terraform exited with code 0.
::debug::stdout: Acquiring state lock. This may take a few moments...%0A%0AApply complete! Resources: 0 added, 0 changed, 0 destroyed.%0AReleasing state lock. This may take a few moments...%0A%0AOutputs:%0A%0Aservice_hmpps_dsd_io_namesevers = [%0A  toset([%0A    "ns1-06.azure-dns.com.",%0A    "ns2-06.azure-dns.net.",%0A    "ns3-06.azure-dns.org.",%0A    "ns4-06.azure-dns.info.",%0A  ]),%0A]%0A
::debug::stderr: 
::debug::exitcode: 0
::set-output name=stdout::Acquiring state lock. This may take a few moments...%0A%0AApply complete! Resources: 0 added, 0 changed, 0 destroyed.%0AReleasing state lock. This may take a few moments...%0A%0AOutputs:%0A%0Aservice_hmpps_dsd_io_namesevers = [%0A  toset([%0A    "ns1-06.azure-dns.com.",%0A    "ns2-06.azure-dns.net.",%0A    "ns3-06.azure-dns.org.",%0A    "ns4-06.azure-dns.info.",%0A  ]),%0A]%0A
::set-output name=stderr::
::set-output name=exitcode::0
```